### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/wayneandstark.github.com#1]
@drnic What's the license for this repo?

**Comment by drnic** [comment]
Can the repo be deleted?

Get Outlook for iOS




On Fri, Dec 2, 2016 at 6:05 AM +1000, "Geoff Franks" <notifications@github.com> wrote:












@drnic What's the license for this repo?

**Comment by geofffranks** [comment]
Beats me, I was just having fun with you :)

Looks like it used to be used for DNS somehow?

**Comment by drnic** [comment]
Back in the day at least one of our customers thought we were Wayne and Stark, and Wayne Seguin didn't dissuade them of it :)



On Fri, Dec 2, 2016 at 7:08 AM +1000, "Geoff Franks" <notifications@github.com> wrote:










Beats me, I was just having fun with you :)



Looks like it used to be used for DNS somehow?

**Comment by geofffranks** [comment]
Going with the deletion route
